package edu.example.dto.fileModel;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class FileModelResponseDto {

    @Schema(description = "File original name")
    private String originalName;

    @Schema(description = "Autogenerated name, by which file was saved in storage")
    private String savedByName;
}
